spring:
  application:
    name: prompt-forge

  datasource:
    url: jdbc:postgresql://localhost:9010/testDB
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api/
      chat:
        options:
          #          model: nvidia/nemotron-3-super-120b-a12b:free
          model: nvidia/nemotron-3-ultra-550b-a55b:free
          #          model: google/gemma-4-26b-a4b-it:free
          #          model : google/gemma-4-31b-it:free
          #          model: thinkingmachines/inkling-small:free
          temperature: 0.0

jwt:
  secret-key: sdkjnbhfjsdahlfuiashdilufjhadliufhhnfjdhai

stripe:
  api:
    secret: sk_test_51TiyS0RiW6TgZoohoSoOB8ChaOPYsRLGltDJYiIuNE6vV9F1lGxNEEHNr8tiC99P0fh6fTmvPwqgQHYG7Lx6bGIa00ifxqwxds
  webhook:
    secret: whsec_b0d52f7483eea1aa6632df741fa63f6fe24605f34a4f71784c0aadc732641ffd

client:
  url: http://localhost:8080

logging:
  level:
    org:
      springframework:
        ai:
          chat.client: DEBUG
          openai: DEBUG
        web:
          client: DEBUG


minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects